### ISSUE TITLE
Docker hub Username and Password unavailable in CLI

### ISSUE THREAD

**Issue by darrentmagic** [Phala-Network/phala-cloud-cli#21]
When attempting to create multiple CVM's, I'm not able to supply the Docker username/password in order for the image referenced in the docker-compose.yml to be pulled in. 

I will note, when creating in the UI, if I copy/paste all my key/values and they include `DSTACK_DOCKER_USERNAME` and `DSTACK_DOCKER_PASSWORD`, after I click out the "advanced features" I see the values populated. Hopefully this helps. 

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/5a29a8e3-464d-4deb-bab3-0b45fef7aa8d" />

**Comment by HashWarlock** [comment]
When using the private docker registry, you will need to add these environment variables to your .env file and add either the private dockerhub registry environment variables or AWS ECR. Then you will aslo need to add them to your compose file. I've updated the CLI to print a log to show where you are using a private registry or not when deploying or upgrading a CVM in v1.0.8.

##### Using a Private Docker Registry

You can deploy images from a private Docker registry by setting the appropriate environment variables.

##### 🔐 DockerHub:
Set these variables:
- `DSTACK_DOCKER_USERNAME` – Your DockerHub username *(required)*
- `DSTACK_DOCKER_PASSWORD` – Your DockerHub password or personal access token *(required)*
- `DSTACK_DOCKER_REGISTRY` – Registry URL (optional, defaults to DockerHub)

##### 🔐 AWS ECR:
Set these variables:
- `DSTACK_AWS_ACCESS_KEY_ID` – AWS access key *(required)*
- `DSTACK_AWS_SECRET_ACCESS_KEY` – AWS secret key *(required)*
- `DSTACK_AWS_REGION` – AWS region of the ECR *(required)*
- `DSTACK_AWS_ECR_REGISTRY` – Full ECR registry URL *(required)*

Once set and added to your docker-compose.yml file, the CLI will automatically authenticate and pull your private image securely.

Example compose file:

```yaml
version: '3.8'

services:
  brave-search:
    image: hashwarlock/brave-search-mcp:v0.0.1
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - DSTACK_DOCKER_USERNAME=${DSTACK_DOCKER_USERNAME}
      - DSTACK_DOCKER_PASSWORD=${DSTACK_DOCKER_PASSWORD}
    restart: unless-stopped

```
